apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aws-ecr-token.serviceAccountName" . }}-role
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  namespace: {{ .Values.serviceAccount.namespace | default "default" }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]