apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aws-ecr-token.serviceAccountName" . }}-rolebinding
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  namespace: {{ .Values.serviceAccount.namespace | default "default" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ecr-token.serviceAccountName" . }}-sa
    namespace: {{ .Values.serviceAccount.namespace | default "default" }}
roleRef:
  kind: Role
  name: {{ include "aws-ecr-token.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io